### ISSUE TITLE
Crashing when used with Nameplate

### ISSUE THREAD

**Issue by ChristinWhite** [Alminoris/ArborealNature#2]
Oddly, I'm getting a crash before startup when enabled with [Nameplate](https://github.com/Globox1997/Nameplate).  [Logs](https://gist.github.com/ChristinWhite/bdff0f32551b380a06cfb8e9096db27a).

#### Versions

Minecraft: 1.21.1
Prism Loader: 9.1
Fabric Loader: 0.16.9
Java: 17.0.12
macOS: 14.6.1 (23G93)

#### Mods Installed

Arboreal Nature: 0.2.5
Cloth Config v15: 15.0.140
Fabric API: 0.109.0+1.21.1
GeckoLib: 4 4.7
Nameplate: 1.1.5
TerraBlender: 4.1.0.5

Only the two conflicting mods and their dependencies.

**Comment by Alminoris** [comment]
The issue is only with the Nameplate mod. It has no direct connection with Arboreal Nature. The issue itself is similar for other mods with custom Geckolib mobs https://github.com/Globox1997/Nameplate/issues/30.
